import type { TrainingLevelDefinition } from "@/types/training";

/** World 6 — Transform and Reconstruct (stages 34–40). */
export const transformAndReconstructLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 34,
    titleKey: "turnTheShape",
    titleFallback: "Turn the Shape",
    mechanicId: "mental-rotation",
    dimensions: ["reaction", "spatial"],
    descriptionFallback: "Mental rotation up to 90 degrees.",
    params: { maxDegrees: 90 },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 35,
    titleKey: "avoidTheMirrorTrap",
    titleFallback: "Avoid the Mirror Trap",
    mechanicId: "mental-rotation",
    dimensions: ["focus", "spatial"],
    descriptionFallback: "Rotation with mirror-image distractors.",
    params: { mirrorDistractors: true },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 36,
    titleKey: "foldItOnce",
    titleFallback: "Fold It Once",
    mechanicId: "paper-fold",
    dimensions: ["memory", "spatial"],
    descriptionFallback: "Single-fold paper folding.",
    params: { folds: 1 },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 37,
    titleKey: "foldAndPunch",
    titleFallback: "Fold and Punch",
    mechanicId: "paper-fold",
    dimensions: ["logic", "spatial"],
    descriptionFallback: "Predicting hole positions.",
    params: { folds: 1, punchHoles: true },
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 38,
    titleKey: "buildItIn3d",
    titleFallback: "Build It in 3D",
    mechanicId: "spatial-construction",
    dimensions: ["strategy", "spatial"],
    descriptionFallback: "2D-to-3D construction.",
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 39,
    titleKey: "changeYourViewpoint",
    titleFallback: "Change your Viewpoint",
    mechanicId: "spatial-orientation",
    dimensions: ["memory", "spatial"],
    descriptionFallback: "Spatial orientation tasks.",
  },
  {
    id: "level-07",
    order: 7,
    globalStage: 40,
    titleKey: "transformationChallenge",
    titleFallback: "Transformation Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Spatial transformation checkpoint.",
  },
];
