import { LESSON1_SECRET_METADATA, LESSON1_SECRET_ORDER, LESSON1_SECRET_QUESTIONS } from "./mental-math/lesson1";

export const MENTAL_MATH_SECRET_ORDER = LESSON1_SECRET_ORDER;
export const MENTAL_MATH_SECRET_METADATA = LESSON1_SECRET_METADATA;
export const MENTAL_MATH_SECRET_QUESTIONS = LESSON1_SECRET_QUESTIONS;
export const MENTAL_MATH_VIDEO_QUESTION_BANK = MENTAL_MATH_SECRET_ORDER.flatMap(
  (secretKey) => MENTAL_MATH_SECRET_QUESTIONS[secretKey] ?? []
);
