import type { TrainingLevelDefinition } from "@/types/training";

/** World 9 — Interference and Uncertainty (stages 55–60). */
export const interferenceAndUncertaintyLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 55,
    titleKey: "detectTheLure",
    titleFallback: "Detect the Lure",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "focus"],
    descriptionFallback: "N-back and Sternberg lure trials.",
    params: { mechanics: ["n-back", "sternberg"], lures: true },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 56,
    titleKey: "mixedSignals",
    titleFallback: "Mixed Signals",
    mechanicId: "challenge-mix",
    dimensions: ["focus", "reaction"],
    descriptionFallback: "Unpredictable Flanker and Stroop trials.",
    params: { mechanics: ["flanker", "stroop"], unpredictable: true },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 57,
    titleKey: "questionTheConclusion",
    titleFallback: "Question the Conclusion",
    mechanicId: "syllogistic-reasoning",
    dimensions: ["logic", "focus"],
    descriptionFallback: "Valid and invalid syllogisms.",
    params: { includeInvalid: true },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 58,
    titleKey: "chooseWithoutCertainty",
    titleFallback: "Choose Without Certainty",
    mechanicId: "route-planning",
    dimensions: ["strategy"],
    descriptionFallback: "Routes with incomplete information.",
    params: { incompleteInfo: true },
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 59,
    titleKey: "similarButDifferent",
    titleFallback: "Similar but Different",
    mechanicId: "mental-rotation",
    dimensions: ["memory", "spatial"],
    descriptionFallback: "Similar rotations and mirror options.",
    params: { mirrorOptions: true },
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 60,
    titleKey: "interferenceChallenge",
    titleFallback: "Interference Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Uncertainty and distraction checkpoint.",
  },
];
