import type { TrainingLevelDefinition } from "@/types/training";

/** World 4 — Update and Switch (stages 21–27). */
export const updateAndSwitchLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 21,
    titleKey: "nameThePreviousItem",
    titleFallback: "Name the Previous Item",
    mechanicId: "n-back",
    dimensions: ["memory", "reaction"],
    descriptionFallback: "1-back mastery.",
    params: { n: 1 },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 22,
    titleKey: "lookTwoStepsBack",
    titleFallback: "Look Two Steps Back",
    mechanicId: "n-back",
    dimensions: ["memory", "focus"],
    descriptionFallback: "Guided 2-back.",
    params: { n: 2, guided: true },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 23,
    titleKey: "changingTargets",
    titleFallback: "Changing Targets",
    mechanicId: "target-update",
    dimensions: ["memory", "focus"],
    descriptionFallback: "Updating target categories.",
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 24,
    titleKey: "switchTheRule",
    titleFallback: "Switch the Rule",
    mechanicId: "classification",
    dimensions: ["logic", "focus"],
    descriptionFallback: "Alternating classification rules.",
    params: { alternatingRules: true },
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 25,
    titleKey: "changingResponses",
    titleFallback: "Changing Responses",
    mechanicId: "choice-reaction",
    dimensions: ["focus", "reaction"],
    descriptionFallback: "Choice reaction time with rule changes.",
    params: { ruleChanges: true },
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 26,
    titleKey: "updateAndPlan",
    titleFallback: "Update and Plan",
    mechanicId: "route-planning",
    dimensions: ["memory", "strategy"],
    descriptionFallback: "Remembering constraints during route planning.",
    params: { rememberConstraints: true },
  },
  {
    id: "level-07",
    order: 7,
    globalStage: 27,
    titleKey: "updateAndSwitchChallenge",
    titleFallback: "Update and Switch Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Updating and rule-switching checkpoint.",
  },
];
