import type { TrainingLevelDefinition } from "@/types/training";

/** World 10 — Integrated Challenges (stages 61–67). */
export const integratedChallengesLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 61,
    titleKey: "rememberThenReason",
    titleFallback: "Remember, Then Reason",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic"],
    descriptionFallback: "Retain information and answer an inference.",
    params: { sequence: ["memory-hold", "inference"] },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 62,
    titleKey: "focusThenPlan",
    titleFallback: "Focus, Then Plan",
    mechanicId: "challenge-mix",
    dimensions: ["focus", "strategy"],
    descriptionFallback: "Filter clues before choosing a route.",
    params: { sequence: ["filter-clues", "route-planning"] },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 63,
    titleKey: "rotateThenChoose",
    titleFallback: "Rotate, Then Choose",
    mechanicId: "challenge-mix",
    dimensions: ["reaction", "spatial"],
    descriptionFallback: "Transform an object and select quickly.",
    params: { sequence: ["mental-rotation", "speeded-choice"] },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 64,
    titleKey: "updateThenNavigate",
    titleFallback: "Update, Then Navigate",
    mechanicId: "route-planning",
    dimensions: ["memory", "strategy"],
    descriptionFallback: "Changing route constraints.",
    params: { changingConstraints: true },
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 65,
    titleKey: "fastButCareful",
    titleFallback: "Fast but Careful",
    mechanicId: "challenge-mix",
    dimensions: ["logic", "focus", "reaction"],
    descriptionFallback: "Timed decisions with interference.",
    params: { timed: true, interference: true },
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 66,
    titleKey: "fullCognitiveChallenge",
    titleFallback: "Full Cognitive Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Sequential multi-domain mission.",
    params: { sequentialMultiDomain: true },
  },
  {
    id: "level-07",
    order: 7,
    globalStage: 67,
    titleKey: "integrationChallenge",
    titleFallback: "Integration Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Fixed integrated checkpoint.",
    params: { fixedCheckpoint: true },
  },
];
