import type { TrainingLevelDefinition } from "@/types/training";

const ALL_DIMS = [
  "memory",
  "logic",
  "focus",
  "reaction",
  "strategy",
  "spatial",
] as const;

/** World 11 — Adaptive Mastery (stages 68–74). All levels tag six dimensions; content is adaptive. */
export const adaptiveMasteryLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 68,
    titleKey: "weakestSkillTraining",
    titleFallback: "Weakest Skill Training",
    mechanicId: "adaptive-mix",
    dimensions: [...ALL_DIMS],
    descriptionFallback: "Practice the learner’s lowest domain.",
    params: { mode: "weakest-domain" },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 69,
    titleKey: "accuracyRepair",
    titleFallback: "Accuracy Repair",
    mechanicId: "adaptive-mix",
    dimensions: [...ALL_DIMS],
    descriptionFallback: "Address frequent error patterns.",
    params: { mode: "error-patterns" },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 70,
    titleKey: "fluencyBuilder",
    titleFallback: "Fluency Builder",
    mechanicId: "adaptive-mix",
    dimensions: [...ALL_DIMS],
    descriptionFallback: "Improve slow but accurate performance.",
    params: { mode: "fluency" },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 71,
    titleKey: "transferTest",
    titleFallback: "Transfer Test",
    mechanicId: "adaptive-mix",
    dimensions: [...ALL_DIMS],
    descriptionFallback: "Present familiar rules with new visuals.",
    params: { mode: "transfer" },
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 72,
    titleKey: "maintenanceMix",
    titleFallback: "Maintenance Mix",
    mechanicId: "adaptive-mix",
    dimensions: [...ALL_DIMS],
    descriptionFallback: "Review strong and previously completed skills.",
    params: { mode: "maintenance" },
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 73,
    titleKey: "adaptiveChallenge",
    titleFallback: "Adaptive Challenge",
    mechanicId: "adaptive-mix",
    dimensions: [...ALL_DIMS],
    descriptionFallback: "Adjust difficulty after each task block.",
    params: { mode: "adaptive-difficulty" },
  },
  {
    id: "level-07",
    order: 7,
    globalStage: 74,
    titleKey: "personalizedMasteryCheck",
    titleFallback: "Personalized Mastery Check",
    mechanicId: "adaptive-mix",
    dimensions: [...ALL_DIMS],
    descriptionFallback: "Measure progress across weak and strong domains.",
    params: { mode: "mastery-check" },
  },
];
