import type { TrainingLevelDefinition } from "@/types/training";

/** World 2 — Hold and Compare (stages 7–13). */
export const holdAndCompareLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 7,
    titleKey: "keepTwoInMind",
    titleFallback: "Keep Two in Mind",
    mechanicId: "sternberg",
    dimensions: ["memory", "focus"],
    descriptionFallback: "Sternberg set size 2–3.",
    params: { setSizeMin: 2, setSizeMax: 3 },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 8,
    titleKey: "spotTheChange",
    titleFallback: "Spot the Change",
    mechanicId: "change-detection",
    dimensions: ["spatial"],
    descriptionFallback: "Change detection with 2–3 objects.",
    params: { objectCountMin: 2, objectCountMax: 3 },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 9,
    titleKey: "chooseTheSignal",
    titleFallback: "Choose the Signal",
    mechanicId: "choice-reaction",
    dimensions: ["focus", "reaction"],
    descriptionFallback: "Two-choice reaction time.",
    params: { choices: 2 },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 10,
    titleKey: "compareTheShapes",
    titleFallback: "Compare the Shapes",
    mechanicId: "mental-rotation",
    dimensions: ["logic", "spatial"],
    descriptionFallback: "Basic mental rotation and shape relations.",
    params: { variant: "basic" },
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 11,
    titleKey: "buildTheChain",
    titleFallback: "Build the Chain",
    mechanicId: "transitive-inference",
    dimensions: ["memory", "logic"],
    descriptionFallback: "Two-step transitive inference.",
    params: { steps: 2 },
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 12,
    titleKey: "oneConstraintRoute",
    titleFallback: "One-Constraint Route",
    mechanicId: "route-planning",
    dimensions: ["logic", "strategy"],
    descriptionFallback: "Route planning with one blocked path.",
    params: { blockedPaths: 1 },
  },
  {
    id: "level-07",
    order: 7,
    globalStage: 13,
    titleKey: "holdAndCompareChallenge",
    titleFallback: "Hold and Compare Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Small-set memory and comparison checkpoint.",
  },
];
