import type { TrainingLevelDefinition } from "@/types/training";

/** World 7 — Plan Ahead (stages 41–47). */
export const planAheadLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 41,
    titleKey: "threeMovesAhead",
    titleFallback: "Three Moves Ahead",
    mechanicId: "route-planning",
    dimensions: ["strategy", "memory"],
    descriptionFallback: "Short route sequences.",
    params: { shortSequences: true },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 42,
    titleKey: "moveTheTower",
    titleFallback: "Move the Tower",
    mechanicId: "hanoi",
    dimensions: ["strategy", "spatial"],
    descriptionFallback: "Three-disc Tower of Hanoi.",
    params: { discs: 3 },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 43,
    titleKey: "avoidTheDeadEnd",
    titleFallback: "Avoid the Dead End",
    mechanicId: "route-planning",
    dimensions: ["strategy", "logic"],
    descriptionFallback: "Routes with misleading paths.",
    params: { misleadingPaths: true },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 44,
    titleKey: "matchTheGoal",
    titleFallback: "Match the Goal",
    mechanicId: "london",
    dimensions: ["strategy", "spatial"],
    descriptionFallback: "London-style goal configuration.",
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 45,
    titleKey: "buildTheSubgoals",
    titleFallback: "Build the Subgoals",
    mechanicId: "route-planning",
    dimensions: ["strategy", "memory"],
    descriptionFallback: "Breaking plans into smaller steps.",
    params: { subgoals: true },
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 46,
    titleKey: "followEveryConstraint",
    titleFallback: "Follow Every Constraint",
    mechanicId: "route-planning",
    dimensions: ["strategy", "focus"],
    descriptionFallback: "Multi-constraint pathfinding.",
    params: { multiConstraint: true },
  },
  {
    id: "level-07",
    order: 7,
    globalStage: 47,
    titleKey: "planningChallenge",
    titleFallback: "Planning Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Multi-step planning checkpoint.",
  },
];
