import type { TrainingLevelDefinition } from "@/types/training";

/** World 3 — Attention Control (stages 14–20). */
export const attentionControlLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 14,
    titleKey: "ignoreTheNoise",
    titleFallback: "Ignore the Noise",
    mechanicId: "flanker",
    dimensions: ["focus", "reaction"],
    descriptionFallback: "Congruent and incongruent Flanker task.",
    params: { includeIncongruent: true },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 15,
    titleKey: "colorConflict",
    titleFallback: "Color Conflict",
    mechanicId: "stroop",
    dimensions: ["logic", "focus"],
    descriptionFallback: "Stroop-style color and word matching.",
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 16,
    titleKey: "searchTheGrid",
    titleFallback: "Search the Grid",
    mechanicId: "schulte-grid",
    dimensions: ["focus", "reaction"],
    descriptionFallback: "Schulte Grid 3×3.",
    params: { size: 3 },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 17,
    titleKey: "rememberThroughDistraction",
    titleFallback: "Remember Through Distraction",
    mechanicId: "change-detection",
    dimensions: ["memory", "focus"],
    descriptionFallback: "Change detection with distractors.",
    params: { withDistractors: true },
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 18,
    titleKey: "chooseByTheRule",
    titleFallback: "Choose by the Rule",
    mechanicId: "choice-reaction",
    dimensions: ["logic", "reaction"],
    descriptionFallback: "Rule-based choice reaction time.",
    params: { ruleBased: true },
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 19,
    titleKey: "routeThroughTheNoise",
    titleFallback: "Route Through the Noise",
    mechanicId: "route-planning",
    dimensions: ["focus", "strategy"],
    descriptionFallback: "Route selection with irrelevant paths.",
    params: { irrelevantPaths: true },
  },
  {
    id: "level-07",
    order: 7,
    globalStage: 20,
    titleKey: "attentionControlChallenge",
    titleFallback: "Attention Control Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Mixed interference checkpoint.",
  },
];
