import type { TrainingLevelDefinition } from "@/types/training";

/** World 8 — Speed with Accuracy (stages 48–54). */
export const speedWithAccuracyLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 48,
    titleKey: "respondConsistently",
    titleFallback: "Respond Consistently",
    mechanicId: "simple-reaction",
    dimensions: ["reaction", "focus"],
    descriptionFallback: "Simple reaction time consistency.",
    params: { consistencyFocus: true },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 49,
    titleKey: "chooseQuickly",
    titleFallback: "Choose Quickly",
    mechanicId: "choice-reaction",
    dimensions: ["reaction", "logic"],
    descriptionFallback: "Two- and four-choice reaction time.",
    params: { choices: [2, 4] },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 50,
    titleKey: "expectTheUnexpected",
    titleFallback: "Expect the Unexpected",
    mechanicId: "simple-reaction",
    dimensions: ["reaction", "focus"],
    descriptionFallback: "Variable stimulus timing.",
    params: { variableTiming: true },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 51,
    titleKey: "stopTheWrongResponse",
    titleFallback: "Stop the Wrong Response",
    mechanicId: "response-inhibition",
    dimensions: ["reaction", "focus"],
    descriptionFallback: "Conflict and response inhibition.",
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 52,
    titleKey: "stayAlert",
    titleFallback: "Stay Alert",
    mechanicId: "pvt",
    dimensions: ["reaction", "focus"],
    descriptionFallback: "PVT-style vigilance.",
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 53,
    titleKey: "rememberUnderTime",
    titleFallback: "Remember Under Time",
    mechanicId: "challenge-mix",
    dimensions: ["reaction", "memory"],
    descriptionFallback: "Timed Sternberg and change detection.",
    params: { mechanics: ["sternberg", "change-detection"], timed: true },
  },
  {
    id: "level-07",
    order: 7,
    globalStage: 54,
    titleKey: "speedAndAccuracyChallenge",
    titleFallback: "Speed and Accuracy Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Timed mixed checkpoint.",
    params: { timed: true },
  },
];
