import type { TrainingLevelDefinition } from "@/types/training";

/** World 5 — Relations and Rules (stages 28–33). */
export const relationsAndRulesLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 28,
    titleKey: "relationshipChains",
    titleFallback: "Relationship Chains",
    mechanicId: "transitive-inference",
    dimensions: ["logic", "memory"],
    descriptionFallback: "Three-link transitive inference.",
    params: { links: 3 },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 29,
    titleKey: "completeThePattern",
    titleFallback: "Complete the Pattern",
    mechanicId: "analogical-reasoning",
    dimensions: ["logic", "spatial"],
    descriptionFallback: "Basic analogical reasoning.",
    params: { variant: "basic" },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 30,
    titleKey: "allSomeAndNone",
    titleFallback: "All, Some, and None",
    mechanicId: "syllogistic-reasoning",
    dimensions: ["logic", "memory"],
    descriptionFallback: "Introductory syllogistic reasoning.",
    params: { variant: "intro" },
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 31,
    titleKey: "reverseTheRelationship",
    titleFallback: "Reverse the Relationship",
    mechanicId: "transitive-inference",
    dimensions: ["logic", "focus"],
    descriptionFallback: "Reversed and negatively phrased relations.",
    params: { reversed: true, negativePhrasing: true },
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 32,
    titleKey: "mapTheHiddenRule",
    titleFallback: "Map the Hidden Rule",
    mechanicId: "classification",
    dimensions: ["logic", "strategy"],
    descriptionFallback: "Rule discovery and structured choices.",
    params: { ruleDiscovery: true },
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 33,
    titleKey: "relationsAndRulesChallenge",
    titleFallback: "Relations and Rules Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Mixed reasoning checkpoint.",
  },
];
