import type { TrainingLevelDefinition } from "@/types/training";

/** World 1 — Foundations (stages 1–6). Named stubs from the design grid. */
export const foundationsLevels: TrainingLevelDefinition[] = [
  {
    id: "level-01",
    order: 1,
    globalStage: 1,
    titleKey: "signalStart",
    titleFallback: "Signal Start",
    mechanicId: "simple-reaction",
    dimensions: ["focus", "reaction"],
    descriptionFallback: "Simple reaction time & choice reaction time.",
    params: { variant: "intro" },
  },
  {
    id: "level-02",
    order: 2,
    globalStage: 2,
    titleKey: "quickMatch",
    titleFallback: "Quick Match",
    mechanicId: "sternberg",
    dimensions: ["memory", "reaction"],
    descriptionFallback: "Two-item Sternberg · target matching.",
    params: { items: 2 },
  },
  {
    id: "level-03",
    order: 3,
    globalStage: 3,
    titleKey: "sameOrDifferent",
    titleFallback: "Same or Different",
    mechanicId: "change-detection",
    dimensions: ["spatial"],
    descriptionFallback: "Basic change detection · shape matching.",
  },
  {
    id: "level-04",
    order: 4,
    globalStage: 4,
    titleKey: "followTheRule",
    titleFallback: "Follow the Rule",
    mechanicId: "classification",
    dimensions: ["logic", "focus"],
    descriptionFallback: "Simple classification and direct relationships.",
  },
  {
    id: "level-05",
    order: 5,
    globalStage: 5,
    titleKey: "firstRoute",
    titleFallback: "First Route",
    mechanicId: "route-planning",
    dimensions: ["strategy", "spatial"],
    descriptionFallback: "Two-step route planning and position matching.",
  },
  {
    id: "level-06",
    order: 6,
    globalStage: 6,
    titleKey: "foundationsChallenge",
    titleFallback: "Foundations Challenge",
    mechanicId: "challenge-mix",
    dimensions: ["memory", "logic", "focus", "reaction", "strategy", "spatial"],
    descriptionFallback: "Short guided challenge using intro tasks from prior stages.",
  },
];
